apiVersion: v1
kind: ReplicationController
metadata:
  name: monitoring-heapster-v4
  namespace: default 
  labels: 
    k8s-app: heapster
    version: v4
    kubernetes.io/cluster-service: "true"
spec: 
  replicas: 1
  selector: 
    k8s-app: heapster
    version: v4
  template: 
    metadata: 
      labels: 
        k8s-app: heapster
        version: v4
        kubernetes.io/cluster-service: "true"
    spec: 
      containers: 
        - image: gcr.io/google_containers/heapster:v0.14.3
          name: heapster
          resources:
            limits:
              cpu: 200m
          command:
            - /heapster
            - --source=kubernetes:http://kubernetes?auth=""
            - --sink=influxdb:http://monitoring-influxdb:8086
          volumeMounts: 
            - name: ssl-certs
              mountPath: /etc/ssl/certs
              readOnly: true
      volumes: 
        - name: ssl-certs
          hostPath: 
            path: "/etc/ssl/certs"
